spring:
  application:
    name: microservice-rest
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_db
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
    show-sql: true